spring: 
  application.name: study
  jackson.serialization.indent-output: true
  jpa.properties.hibernate.format_sql: true

logging:
 level:
  root: info
  com.example.demo: trace
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.hibernate.orm.jdbc.extract: trace
#  org.springframework.transaction: trace
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG


#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password: 
#spring.jpa.hibernate.ddl-auto: create
#spring.jpa.show-sql: true
